### ISSUE TITLE
DocumentCommitThread raises errors after injecting PyDocstring

### ISSUE THREAD

**Issue by koxudaxi** [pauleveritt/htmpy-pycharm-plugin#15]
@sproshev
Would you help me to resolve this error?
I'm implementing that the plugin injects `Python` into `HTML`. (https://github.com/pauleveritt/htmpy-pycharm-plugin/issues/4)
I'm trying multiple injecting for one PyStringLiteralElement.

Example:
![2020-12-24 10 48 17](https://user-images.githubusercontent.com/630670/103049619-9ed45c00-45d5-11eb-81e5-b1558fcb4819.png)

In this situation, the plugin injects three words.
- {Heading}
- assigned values for `name` and `age`.

Code:
https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/186758c1207271843340786babd399504983c221/src/com/koxudaxi/htmpy/HtmpyInjector.kt#L68-L75

I think the implementation works fine.
But, when I enter a single quote into this PyStringLiteralExpression, This String will be split and PyCharm raises out of range error.
 
 This way can reproduce.
1. set valid value like "abc" 
> html('<div><{Heading} name="abc" />')

2. type single quote. PyCharm input two single quote.
> html('<div><{Heading} name=''"abc" />')

3. raise errors
```
java.lang.RuntimeException: After patch: doc:
'Heading(name=''"abc")'
---PSI:
'Heading(name="abc")'
---chars:
'Heading(name="abc")'.
OK let's see. Host file: PyFile:main.py in '/Users/koudai/PycharmProjects/pythonProject1/main.py' (Language: Python)  (uncommitted)
Was injected Language: PyDocstring at ranges: [Shred prefix='Heading(name=' suffix=')' in PyStringLiteralExpression: <div><{Heading} name="abc" /> with range (286,319) (class com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl) inside range (22,29)]
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.parseFile(InjectionRegistrarImpl.java:699)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.reparse(InjectionRegistrarImpl.java:611)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.reparse(InjectedLanguageUtil.java:376)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.reparseChangedInjectedFragments(PsiDocumentManagerImpl.java:176)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:298)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:135)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitAsynchronously$0(DocumentCommitThread.java:81)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I was investigating the causes.
This error happened before injecting PyDocstring for a single quote.
It means this error comes from Pychrm commit a single quote to the document.
I can't handle this error in this plugin.

Thank you

**Comment by koxudaxi** [comment]
@sproshev
Would you please check this issue?

**Comment by sproshev** [comment]
@koxudaxi Hi! I asked @east825 for help since he is more familiar with strings processing.

**Comment by koxudaxi** [comment]
Hi, @sproshev (and @east825). 
Did you find out about the problem?
Thank you.

**Comment by east825** [comment]
Hi @koxudaxi. Not yet, but I've seen something similar among my exception reports. I'll take a look and try to help next week. Sorry, it takes so long.

**Comment by koxudaxi** [comment]
@east825 
Thank you for your quick reply!!
No problem, I look forward to your response.

**Comment by east825** [comment]
@koxudaxi I took a quick look at the plugin. I can reproduce the problem and am yet to figure out what's going on, but there is one thing that bothers me in the current implementation. Why did you decide to inject `PyDocstringLanguageDialect` into values of tag attributes in addition to `HtmpyLanguage` already being a template language? You effectively perform two-layer injecting in a string literal (`PyDocstringLanguageDialect` on top of  `HtmpyLanguage`), and I'm not quite sure that the platform can properly handle that. Having three different languages in a single string element seems too much to me :) Wouldn't it be simpler to require surrounding all Python expressions with curly braces (as in f-strings)? This way you will need to only inject `HtmpyLanguage` in an entire literal and it will take care of all the embedded Python automatically. Do I miss something in how htm.py works?

**Comment by east825** [comment]
The original problem is most likely [PY-36664](https://youtrack.jetbrains.com/issue/PY-36664). I will try to come up with a fix, follow the ticket to be notified of the progress.

**Comment by east825** [comment]
Also, if these injections in tag attributes are needed only for code completion, to me it seems safer just to implement a dedicated completion contributor. Language injections are not very fast and can be brittle (as you see), better not to overuse them if you can. If you want completion results like in real Python code, there are ways to emulate that by running a completion in a synthetic in-memory file and then re-using these variants in your context. For instance, we do such a thing after an openening curly brace in normal string literals as if it was an f-string. Check `PyFStringLikeCompletionContributor` (`PyUtil.createExpressionFromFragment(...)` part).

**Comment by koxudaxi** [comment]
@east825 

> Why did you decide to inject PyDocstringLanguageDialect into values of tag attributes in addition to HtmpyLanguage already being a template language?

I guess ` htm.py` needs multiple-layer injecting in a string literal.
example:
```python
@dataclass
class Heading:
    name: str
    age: int
     
     def __call__(self) -> VDOM:
        return html('<h1>Hello {self.name}</h1>')
html('<div><{Heading} name="dog" age=10 /></div>')
```
The layers are below.

1. HtmpyLanguage (HTML language) -> `<div>...</div>`
2. PyDocstringLanguageDialect (Python language in `{}` )->  `{Heading}`
3. PyDocstringLanguageDialect (Python language in virtual code fragment) -> `Heading(name="dog" age=10)` is genereged from `<{Heading} name="dog" age=10 />`

> I'm not quite sure that the platform can properly handle that. Having three different languages in a single string element seems too much to me :)

Me too. I don't want to do it. :(

> Wouldn't it be simpler to require surrounding all Python expressions with curly braces (as in f-strings)?

I think that this way doesn't cover virtual code fragments.
Is it wrong?
> 3. PyDocstringLanguageDialect (Python language in virtual code fragment) -> `Heading(name="dog" age=10)` is genereged from `<{Heading} name="dog" age=10 />`



> Also, if these injections in tag attributes are needed only for code completion, to me it seems safer just to implement a dedicated completion contributor. 

We will need type-checking, resolving references, refactoring variable names, etc.

Would you have another approach? 

Thank you!!

**Comment by east825** [comment]
@koxudaxi 

Oh, right, I haven't thought about type checking of these values. It makes things more difficult. Tell me more about what can be used as an argument for `name='foo'` attributes. If only string literals in quotes and int/float literals can be used as-is, without enclosing braces, it looks doable. You can add an inspection for HTML language that checks that for such tag attributes the respective Python attributes are of the right type. And as for Python fragments inside "{}", you can add another minimal custom inspection that uses `PyTypeChecker` directly.

Renaming tag attributes, in general, don't seem a huge problem, you'd just need to register a corresponding `PsiReferenceContributor` that will add PSI references pointing back to the class attributes from these names. For instance, we do the same thing for names like "{name}" and "%(name)s" for formatted strings in Python (`PythonFormattedStringReferenceContributor`). Once you have references, Find Usages and Rename will start to work automatically.

Yes, it's all extra work but it's also a much more robust and well-known (at least to me) solution than layered language injections.

**Comment by pauleveritt** [comment]
> @koxudaxi
> 
> Oh, right, I haven't thought about type checking of these values. It makes things more difficult. Tell me more about what can be used as an argument for `name='foo'` attributes. 

You can have a literal in quotes, an expression in quotes, a mixture of literal and expression in quotes, and you can leave the quotes out entirely:

```
<{Heading} name="World" />
<{Heading} name="{name} !" />
<{Heading} name={`World`} />
```

**Comment by koxudaxi** [comment]
@pauleveritt 
Thank you for explaining the behavior.
I feel it is very flexible.
Can we use a variable for an argument? 

@east825
> You can add an inspection for HTML language that checks that for such tag attributes the respective Python attributes are of the right type. And as for Python fragments inside "{}", you can add another minimal custom inspection that uses PyTypeChecker directly.

Do I have to parse the text as `PyElement` in the inspections to realize the implementation?.
I wrote custom `PyTypeCheckerInspection`for [pydantic plugin](https://github.com/koxudaxi/pydantic-pycharm-plugin/blob/master/src/com/koxudaxi/pydantic/PydanticTypeCheckerInspection.kt). 
I remember that `PyTypeChecker` expects  `PyType` as an arguemnt.
A Visitor method of HTML Langage doesn't provide `PyElement` to me.


I don't know `PsiReferenceContributor`.  It's good news.
But, If an attribute has an expression then It's difficult to resolve a variable in an expression. :(

> Yes, it's all extra work but it's also a much more robust and well-known (at least to me) solution than layered language injections.

OK, I'm slowly but surely improving.

**Comment by pauleveritt** [comment]
> @pauleveritt
> Thank you for explaining the behavior.
> I feel it is very flexible.
> Can we use a variable for an argument?

Can you describe this a little more?

**Comment by koxudaxi** [comment]
@pauleveritt 
OK, I care about this case.  we may need to detect each variable in the expression.
```python
first_name: str = 'abc'
last_name: str = 'efg'
html('<{Heading} name="{first_name + last_name}" />')
```

**Comment by pauleveritt** [comment]
@koxudaxi Good point, putting ternaries in an attribute value is an important pattern.

**Comment by koxudaxi** [comment]
@pauleveritt 
Thank you! We have to parse the expression for each variable.
And, We should inspect the expression is correct python expression syntax 🤔

**Comment by pauleveritt** [comment]
As more FYI, WebStorm has a similar need in their support for htm/lit-html. The background is [described in the IntelliJ section here](https://open-wc.org/guides/tools/ide/#intellij-idea-and-other-jetbrains-variants). That is: an `html` "tagged template", with (a) HTML contents and (b) curly brackets (c) that can have language (JS) expressions and (d) autocomplete and (e) special symbol semantics.

Here's [a plugin](https://plugins.jetbrains.com/plugin/7312-polymer--web-components) and there are various tickets about syntax in HTML.

**Comment by east825** [comment]
@koxudaxi 
> A Visitor method of HTML Langage doesn't provide PyElement to me.

That's correct. You will have to work with an instance of `XmlAttribute`. But if the value of an attribute is something in quotes, I guess, you can assume that the actual type of it is just a string and you can get it with `PyBuiltinCache#getStringType` and then pass to `PyTypeChecker`. Same thing for number literals (`PyBuiltinCache#getIntType`/`PyBuiltinCache#getFloatType`). To get the expected Python type you will need to switch to the Python file within the same document and fiddle with Python PSI and resolve as usual. 

My idea is that there is a limited set of possible values for HTML attributes. Seemingly it's either a quoted value (`"spam"` or `"foo{bar}"`), a numeric literal (42, 3.14), or something in braces, but in the latter case, the parser has already embedded a Python fragment there for you and you have access to the full Python PSI.

> And, We should inspect the expression is correct python expression syntax.

If your template language's parser will treat anything in curly braces as Python fragments (you already do it for `<{Heading} ..>`),
Python parser and annotators will take care of this validation for you.

@pauleveritt 
What's the type of the argument "arg" in `<{Heading} arg="{foo}" />`? Is it the value of `foo` reference expression in Python or always a string, similar to `f"{foo}"`?

**Comment by pauleveritt** [comment]
> @pauleveritt
> What's the type of the argument "arg" in `<{Heading} arg="{foo}" />`? Is it the value of `foo` reference expression in Python or always a string, similar to `f"{foo}"`?

That template is a "direct" call of the following:

```python
@dataclass
class Heading:
    arg: str

    def __call__(self) -> VDOM:
        return ...
```

**Comment by east825** [comment]
@pauleveritt I see, but I meant not the interpretation of the entire tag, but specifically `"{foo}"` part. Is it `Heading(arg=foo)()` or `Heading(arg=str(foo))()`? I'd like to understand is there a difference between `arg="{foo}"` and `arg={foo}` syntax.

**Comment by pauleveritt** [comment]
@east825 Much more the former, `Heading(arg=foo)()`.

**Comment by koxudaxi** [comment]
@pauleveritt 
> Here's a plugin and there are various tickets about syntax in HTML.

It's an interesting plugin. But, Not OSS, I can't watch source code :(
I want to know how to implement it.

**Comment by koxudaxi** [comment]
@east825 
I didn't know about PyBuiltinCache. Thank you.

OK, I see your strategy.
We will parse curly braces as Python fragments. And literals are parsed and check type with `PyBuiltinCache` and `PyTypeChecker`.

@pauleveritt  What did you think about this strategy?  Is there a missed pattern?

**Comment by pauleveritt** [comment]
@koxudaxi I can't think of a missed pattern, though I have a terrible feeling we're missing something. 😄 Either way, let's use this milestone for just that refactoring. Even if it fails, I will consider it completed. We can then make the features in the current milestone part of the next one.

**Comment by koxudaxi** [comment]
I believe We resolved the problem.
Thank you!!
