### ISSUE TITLE
PyCharm doesn't detect deep injected python's expression.

### ISSUE THREAD

**Issue by koxudaxi** [pauleveritt/htmpy-pycharm-plugin#4]
This plugin should treat deep injected python's expression.
But, It does not work.
We want that the plugin provides some features for deep injected python's expression. The features are auto-completion, inspection, searching referenced variables, and more.

There is an example here.

![Screenshot_2020-10-04_02-30-01](https://user-images.githubusercontent.com/630670/95018584-abfb4200-069b-11eb-8f12-35e68100e5ba.png)

This plugin can inject `{}` as Python's expression in HTML contents.

`123` is PyNumericLiteralExpression in the PSI Tree.
However, the position is 0. It's shown a red box in the first line. 
I guess It may be the reason for the problem.

This code is creating PyExpression from `{}.`
https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/8ddf5a694e3bc7b4c80d7a163e26492bd6be4847/src/com/koxudaxi/htmpy/psi/impl/HtmpyPsiImplUtil.kt#L24

## Related Issues
https://github.com/pauleveritt/htmpy-pycharm-plugin/issues/2

**Comment by sproshev** [comment]
I assume the position is taken from `com.intellij.psi.PsiElement#getTextOffset` or something similar which is zero for elements created with `com.jetbrains.python.psi.PyUtil#createExpressionFromFragment` (since they are the first elements in synthetic psi file).

Possible idea: what do you think of injecting python language to `{}` inside htmpy language host? We could try with `com.intellij.lang.injection.MultiHostInjector`, see `com.jetbrains.python.codeInsight.typing.PyTypingAnnotationInjector` for example. Method `com.intellij.lang.injection.MultiHostRegistrar#addPlace` should give an ability to specify range inside htmpy language host.

**Comment by koxudaxi** [comment]
@sproshev 
Thank you for your advice.
I will try `MultiHostRegistrar`  to inject python language to `{}`.

**Comment by koxudaxi** [comment]
@sproshev 
I have tried MultiHostRegistrar. 
But, `MultiHostRegistrar#getLanguagesToInject` can't get HtmpyPythonElement.
https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/d3221145a82d51d5a1bb155319d972c58bf2e1e6/src/com/koxudaxi/htmpy/HtmpyInjector.kt#L10-L12
I assume that `MultiHostInjector` is not supported in the nested injected language. because htmpy language is injected in python language.
The thought is correct?

Can I use `getLanguagesToInject` with parsed htmpy language element?

**Comment by koxudaxi** [comment]
@sproshev 
Would you please tell me an idea to resolve the problem?

**Comment by sproshev** [comment]
@koxudaxi I wanted to try one more idea but I'd better share it with you:

* Implement one injector that receives expected host
* Inject in this host both languages (hence `only-injection.xml` should be re-implemented programatically)
* As a result we will see if intellij allows to inject several languages into the same host

**Comment by koxudaxi** [comment]
@sproshev 
Thank you for the idea.
It's interesting, I will try it!!

**Comment by koxudaxi** [comment]
@sproshev 
I have tried your approach.
It works fine.
Also, I use `PyDocstringLanguageDialect` to resolve the referenced variables.

This implementation is not perfect, but It's good to start point.
Thank you very much.

![Screenshot_2020-11-05_18-14-54](https://user-images.githubusercontent.com/630670/98221302-d25e1700-1f92-11eb-88b7-f2d7f1dc5729.png)


https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/b194dda9c34f03968b968b345090916da9b722dd/src/com/koxudaxi/htmpy/HtmpyInjector.kt#L42-L55

**Comment by pauleveritt** [comment]
@koxudaxi I believe this is complete. If there are other aspects still open, let's make some new tickets.
