### ISSUE TITLE
M2: Unresolved component in list comprehension

### ISSUE THREAD

**Issue by pauleveritt** [pauleveritt/htmpy-pycharm-plugin#7]
This snippet gives an unresolved symbol on `sidebar`:

```python
[html('<{sidebar} />') for sidebar in self.sidebars]
```

Here's a screenshot:

<img width="1028" alt="unresolved" src="https://user-images.githubusercontent.com/455142/99149329-46678180-265b-11eb-960a-166f1047f1f0.png">

**Comment by koxudaxi** [comment]
I have fixed and pushed it to https://github.com/pauleveritt/htmpy-pycharm-plugin/pull/3.
I cover some comprehensions.

![Screenshot_2020-11-15_05-51-30](https://user-images.githubusercontent.com/630670/99156738-be3eb600-2706-11eb-82b0-48097ad8ad59.png)

**Comment by pauleveritt** [comment]
This is fixed and confirmed as working.
